# Production Docker Compose Configuration
# 
# This is a convenience file that references the actual configuration
# For the real configuration, see: docker/docker-compose.prod.yml
#
# Usage:
#   docker compose up              # Start production environment
#   npm run start                  # Alternative using npm script
#
# For development:
#   docker compose -f docker/docker-compose.dev.yml up
#   npm run dev:docker             # Alternative using npm script

services:
  # Import from actual production configuration
  api:
    extends:
      file: docker/docker-compose.prod.yml
      service: api

  db:
    extends:
      file: docker/docker-compose.prod.yml
      service: db

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    name: postgres-data